apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "rbac.fullname" . }}-binding
  labels:
  {{- include "rbac.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "rbac.fullname" . }}-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "rbac.fullname" . }}-event-creator-service'
  namespace: '{{ .Release.Namespace }}'