apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: event-creator-service-binding
  labels:
  {{- include "rbac.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: event-creator-service
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: event-creator-service-role