apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rbac.fullname" . }}-event-creator-service
  labels:
  {{- include "rbac.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventCreatorService.serviceAccount.annotations | nindent 4 }}