apiVersion: v1
kind: ServiceAccount
metadata:
  name: event-creator-service
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "rbac.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.eventCreatorService.serviceAccount.annotations | nindent 4 }}