apiVersion: v1
kind: Service
metadata:
  name: {{ include "service1.fullname" . }}-echo-service1-v1
  labels:
  {{- include "service1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.echoService1V1.type }}
  selector:
    app: echo-service1
  {{- include "service1.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.echoService1V1.ports | toYaml | nindent 2 -}}