apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "service1.fullname" . }}-ingress-gateway-app1
  labels:
  {{- include "service1.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "service1.fullname" . }}-echo-service1-v1'
            port:
              number: 5281
        path: /echoserver_app1(/|$)(.*)
        pathType: Prefix