echoService1Deployment:
  echoService1:
    env:
      subtendingServiceName: sub-service-echo-subtending-service-v1
      subtendingServicePort: "5281"
    image:
      repository: ghcr.io/brooksyott/k8s-echo-server-sharp
      tag: v1.0.0
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
  replicas: 1
echoService1V1:
  ports:
    - port: 5281
      protocol: TCP
      targetPort: 5281
  type: ClusterIP
kubernetesClusterDomain: cluster.local
