apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: ingress-nginx
  {{- include "nginx.labels" . | nindent 4 }}
spec:
  controller: k8s.io/ingress-nginx