apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sub-service.fullname" . }}-echo-subtending-service
  labels:
  {{- include "sub-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.echoSubtendingService.replicas }}
  selector:
    matchLabels:
      app: echo-subtending-service
    {{- include "sub-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: echo-subtending-service
      {{- include "sub-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.echoSubtendingService.echoSubtendingService.image.repository
          }}:{{ .Values.echoSubtendingService.echoSubtendingService.image.tag | default
          .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.echoSubtendingService.echoSubtendingService.imagePullPolicy
          }}
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5281
          initialDelaySeconds: 15
          periodSeconds: 20
        name: echo-subtending-service
        ports:
        - containerPort: 5281
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5281
        resources: {{- toYaml .Values.echoSubtendingService.echoSubtendingService.resources
          | nindent 10 }}
      serviceAccountName: event-creator-service