apiVersion: v1
kind: Service
metadata:
  name: {{ include "sub-service.fullname" . }}-echo-subtending-service-v1
  labels:
  {{- include "sub-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.echoSubtendingServiceV1.type }}
  selector:
    app: echo-subtending-service
  {{- include "sub-service.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.echoSubtendingServiceV1.ports | toYaml | nindent 2 -}}