apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sub-service.fullname" . }}-ingress-gateway-subtending-service
  labels:
  {{- include "sub-service.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - backend:
          service:
            name: '{{ include "sub-service.fullname" . }}-echo-subtending-service-v1'
            port:
              number: 5281
        path: /echoserver-sub(/|$)(.*)
        pathType: Prefix