#sammple helmfile to apply helm charts, with dependencies
helmDefaults:
  wait: true
  createNamespace: true


environments:
  default:
    values:
      - my_var: myvalue

releases:
  - name: ingress-nginx
    chart: demo/nginx
    namespace: ingress-nginx
    wait: true
    # values and configurations for myapp1

  - name: rbac
    chart: demo/rbac
    namespace: dependency-demo
    wait: true
    # values and configurations for myapp1

  - name: sub-service
    chart: demo/sub-service
    namespace: dependency-demo
    wait: true
    # values and configurations for myapp1

  - name: service1
    chart: demo/service1
    namespace: dependency-demo
    hooks:
      - events: ["presync", "preapply"]
        showlogs: true
        command: "helmfile"
        args: ["--selector", "name=rbac", "sync"]
      - events: ["presync", "preapply"]
        showlogs: true
        command: "helmfile"
        args: ["--selector", "name=sub-service", "sync"]

  - name: service2
    chart: demo/service2
    namespace: dependency-demo
    hooks:
      - events: ["presync", "preapply"]
        showlogs: true
        command: "helmfile"
        args: ["--selector", "name=rbac", "sync"]
      - events: ["presync", "preapply"]
        showlogs: true
        command: "helmfile"
        args: ["--selector", "name=sub-service", "sync"]
      - events: ["postuninstall"]
        showlogs: true
        command: "echo"
        args:
          [
            "this is a post delete hook, my_var is: {{ .Environment.Values.my_var }}",
          ]
