apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-subtending-service
  namespace: dependency-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-subtending-service
  template:
    metadata:
      labels:
        app: echo-subtending-service
    spec:
      serviceAccountName: event-creator-service
      containers:
        - name: echo-subtending-service
          image: k8s-echo-server-sharp:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5281
          livenessProbe:
            httpGet:
              path: /health/live
              port: 5281
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 5281
---
apiVersion: v1
kind: Service
metadata:
  name: echo-subtending-service-v1
  namespace: dependency-demo
spec:
  selector:
    app: echo-subtending-service
  ports:
    - port: 5282
      targetPort: 5281
